/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PromptHistoryEntry {
    promptOutput: string;
    timestamp: bigint;
    promptInput: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type ApiKey = string;
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UserPublic {
    id: string;
    email: string;
    createdAt: bigint;
    plan: string;
    requestsToday: bigint;
    lastRequestDate: bigint;
    role: string;
    stripeCustomerId: string;
    stripeSubscriptionId: string;
}
export type AuthResult = { ok: string } | { err: string };
export type PromptResult = { ok: string } | { err: string };
export interface backendInterface {
    getApiKey(caller: Principal): Promise<ApiKey>;
    getPromptHistory(callerOnly: boolean): Promise<Array<PromptHistoryEntry>>;
    isApiKeyRegistered(): Promise<boolean>;
    isApiKeyRegisteredWithSession(sessionToken: string): Promise<boolean>;
    makePromptRequest(sceneDetails: string): Promise<string>;
    makePromptRequestWithSession(sessionToken: string, promptContent: string): Promise<PromptResult>;
    registerOpenAiApiKey(openAiApiKey: string): Promise<void>;
    registerOpenAiApiKeyWithSession(sessionToken: string, openAiApiKey: string): Promise<void>;
    testPrompt(): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    signUp(email: string, password: string): Promise<AuthResult>;
    login(email: string, password: string): Promise<AuthResult>;
    logout(sessionToken: string): Promise<void>;
    getCurrentUser(sessionToken: string): Promise<[] | [UserPublic]>;
    getAllUsers(sessionToken: string): Promise<Array<UserPublic>>;
    adminSetPlan(sessionToken: string, email: string, plan: string): Promise<boolean>;
    adminSetSubscription(sessionToken: string, email: string, status: string): Promise<boolean>;
    adminSetRole(sessionToken: string, email: string, role: string): Promise<boolean>;
    adminResetUsage(sessionToken: string, email: string): Promise<boolean>;
    adminDeleteUser(sessionToken: string, email: string): Promise<boolean>;
    setUserPlan(sessionToken: string, plan: string): Promise<boolean>;
    _initializeAccessControlWithSecret(secret: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getApiKey(arg0: Principal): Promise<ApiKey> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiKey(arg0);
            return result;
        }
    }
    async getPromptHistory(arg0: boolean): Promise<Array<PromptHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromptHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromptHistory(arg0);
            return result;
        }
    }
    async isApiKeyRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isApiKeyRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isApiKeyRegistered();
            return result;
        }
    }
    async isApiKeyRegisteredWithSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isApiKeyRegisteredWithSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.isApiKeyRegisteredWithSession(arg0);
        }
    }
    async makePromptRequest(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.makePromptRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makePromptRequest(arg0);
            return result;
        }
    }
    async makePromptRequestWithSession(arg0: string, arg1: string): Promise<PromptResult> {
        if (this.processError) {
            try {
                const result = await this.actor.makePromptRequestWithSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.makePromptRequestWithSession(arg0, arg1);
        }
    }
    async registerOpenAiApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOpenAiApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOpenAiApiKey(arg0);
            return result;
        }
    }
    async registerOpenAiApiKeyWithSession(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.registerOpenAiApiKeyWithSession(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.registerOpenAiApiKeyWithSession(arg0, arg1);
        }
    }
    async testPrompt(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.testPrompt();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.testPrompt();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async signUp(email: string, password: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.signUp(email, password);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.signUp(email, password);
        }
    }
    async login(email: string, password: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(email, password);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.login(email, password);
        }
    }
    async logout(sessionToken: string): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.logout(sessionToken);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.logout(sessionToken);
        }
    }
    async getCurrentUser(sessionToken: string): Promise<[] | [UserPublic]> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser(sessionToken);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.getCurrentUser(sessionToken);
        }
    }
    async getAllUsers(sessionToken: string): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers(sessionToken);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.getAllUsers(sessionToken);
        }
    }
    async adminSetPlan(sessionToken: string, email: string, plan: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetPlan(sessionToken, email, plan);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.adminSetPlan(sessionToken, email, plan);
        }
    }
    async adminSetSubscription(sessionToken: string, email: string, status: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetSubscription(sessionToken, email, status);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.adminSetSubscription(sessionToken, email, status);
        }
    }
    async adminSetRole(sessionToken: string, email: string, role: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetRole(sessionToken, email, role);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.adminSetRole(sessionToken, email, role);
        }
    }
    async adminResetUsage(sessionToken: string, email: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetUsage(sessionToken, email);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.adminResetUsage(sessionToken, email);
        }
    }
    async adminDeleteUser(sessionToken: string, email: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(sessionToken, email);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.adminDeleteUser(sessionToken, email);
        }
    }
    async setUserPlan(sessionToken: string, plan: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserPlan(sessionToken, plan);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.setUserPlan(sessionToken, plan);
        }
    }
    async _initializeAccessControlWithSecret(secret: string): Promise<void> {
        try {
            await (this.actor as any)._initializeAccessControlWithSecret(secret);
        } catch {
            // authorization mixin may not be present; ignore gracefully
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
